In [1]:
from pyuvdata import UVData
from matplotlib import pyplot as plt
import numpy as np

In [2]:
uvd = UVData()

In [3]:
uvd.read_uvh5('Gen1.1.uvh5')

In [4]:
uvd.uvw_array[1]

array([-6.7510000e+00, -1.2982000e+01, -4.9999999e-03])

In [5]:
vis = uvd.get_data(40,41, "XX")

In [6]:
vis.shape

(1, 1)

In [7]:
uvd.read_uvh5('Gen1.1_herasim.uvh5')

Telescope hera_sim is not in known_telescopes.


In [8]:
uvd.uvw_array[1]

array([-6.75100000e+00, -1.29820000e+01, -4.99999977e-03])

In [9]:
vis_herasim = uvd.get_data(0,1, "XX")

In [10]:
vis_herasim.shape

(1, 1)

In [11]:
np.abs(vis), np.abs(vis_herasim)

(array([[6.20898692]]), array([[6.20898593]]))

In [12]:
np.angle(vis), np.angle(vis_herasim)

(array([[-1.1169914]]), array([[1.11699135]]))